-- Phase 19: Agent Insights storage
CREATE TABLE IF NOT EXISTS agent_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id text NOT NULL,
  source_table text NOT NULL,
  source_id uuid,
  insight_type text,
  summary text,
  confidence numeric,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE agent_insights ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_agent_insights_source
  ON agent_insights (source_table, source_id);

COMMENT ON TABLE agent_insights IS 'Structured insights generated by autonomous research agents.';
COMMENT ON COLUMN agent_insights.meta IS 'Optional structured payload (JSON) containing supporting details.';
